/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ass.ui;

import ass.user.Customer;
import ass.user.User;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author hany31
 */
public class ModifyDeleteBook extends javax.swing.JFrame {

    /**
     * Creates new form ModifyBook
     */
    public ModifyDeleteBook() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
	String SelectedBookID = null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelprice = new javax.swing.JLabel();
        jTextFieldprice = new javax.swing.JTextField();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabeltitle = new javax.swing.JLabel();
        jTextFieldtitle = new javax.swing.JTextField();
        jLabelpublisher = new javax.swing.JLabel();
        jTextFieldpublisher = new javax.swing.JTextField();
        jLabelauthor = new javax.swing.JLabel();
        jTextFieldauthor = new javax.swing.JTextField();
        jLabelshopName = new javax.swing.JLabel();
        jTextFieldshopName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabeleISBN = new javax.swing.JLabel();
        jLabeletitle = new javax.swing.JLabel();
        jLabelepublisher = new javax.swing.JLabel();
        jLabeleauthor = new javax.swing.JLabel();
        jLabeleshopname = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 480));

		User newUser = new Customer();
		jTable1  = newUser.listAllBook();
		this.getContentPane().add(jTable1.getTableHeader());
		this.getContentPane().add(jTable1);
		
		
		jTable1.addMouseListener(new MouseAdapter() {
		    public void mousePressed(MouseEvent me) {
		        JTable table =(JTable) me.getSource();
		        Point p = me.getPoint();
		        int selRow = table.rowAtPoint(p);
		        SelectedBookID = jTable1.getValueAt(selRow,0).toString();
		        
		        String prices,ISBNs,titles,publishers,authors,shopNames; 
		        
		        try{
					prices = jTable1.getValueAt(selRow,1).toString().trim();
					jTextFieldprice.setText(prices);
					}
					catch(NullPointerException e){
						jTextFieldprice.setText("");
					}
		        
				try{
					ISBNs = jTable1.getValueAt(selRow,3).toString().trim();
					jTextFieldISBN.setText(ISBNs);
					}
					catch(NullPointerException e){
						jTextFieldISBN.setText("");
					}
				
				try{
					    titles = jTable1.getValueAt(selRow,4).toString().trim();
					    jTextFieldtitle.setText(titles);
						}
						catch(NullPointerException e){
							jTextFieldtitle.setText("");
				        }
			    
				try{
						publishers = jTable1.getValueAt(selRow,5).toString().trim();
						jTextFieldpublisher.setText(publishers);
						}
						catch(NullPointerException e){
							jTextFieldpublisher.setText("");
				        }
				
				try{
				authors = jTable1.getValueAt(selRow,6).toString().trim();
				jTextFieldauthor.setText(authors);
					}
					catch(NullPointerException e){
						jTextFieldauthor.setText("");
			        }

				try{
				shopNames = jTable1.getValueAt(selRow,7).toString();
				jTextFieldshopName.setText(shopNames);	
				}
				catch(NullPointerException e){
					jTextFieldshopName.setText(" ");	
				}

		        }
		    
		});
		
		
		
		;
		
//	jTable1.addMouseListener(new TableListener());
//		
//		class TableListener extends MouseAdapter {
//			public void mouseClicked(final MouseEvent e) {
//				String prices,ISBNs,titles,publishers,authors,shopNames;
//				int selRow = jTable1.getSelectedRow();
//				prices = jTable1.getValueAt(selRow, 1).toString().trim();
//				ISBNs = jTable1.getValueAt(selRow, 3).toString().trim();
//				titles = jTable1.getValueAt(selRow, 4).toString().trim();
//				publishers = jTable1.getValueAt(selRow, 5).toString().trim();
//				authors = jTable1.getValueAt(selRow, 6).toString().trim();
//				shopNames = jTable1.getValueAt(selRow, 7).toString().trim();
//				
//				jTextFieldprice.setText(prices);
//				jTextFieldISBN.setText(ISBNs);
//				jTextFieldtitle.setText(titles);
//				jTextFieldpublisher.setText(publishers);
//				jTextFieldauthor.setText(authors);
//				jTextFieldshopName.setText(shopNames);				
//			}
//		}
		
        jScrollPane1.setViewportView(jTable1);

        jLabelprice.setText("Price:");

        jLabelISBN.setText("ISBN:");

        jLabeltitle.setText("Title:");

        jLabelpublisher.setText("Publisher:");

        jLabelauthor.setText("Author:");

        jLabelshopName.setText("ShopName:");

        jButton1.setText("Modify");
        jButton1.addActionListener(new ActionListener() {
            
			public void actionPerformed(ActionEvent arg0) {
				
			//price
				if (!validPrice(jTextFieldprice.getText())){
					jTextFieldprice.setText("");
					JOptionPane.showMessageDialog(null,"Please input a valid price.");					
					return;
				}
				//ISBN
				if (jTextFieldISBN.getText().isEmpty()){
					jTextFieldISBN.setText("");
					JOptionPane.showMessageDialog(null,"ISBN cannot be empty.");	
					return;
				}
				//title
				if (jTextFieldtitle.getText().equals("")){
					jTextFieldtitle.setText("");
					JOptionPane.showMessageDialog(null,"Title cannot be empty.");
					return;
				}
				//publisher
				if (jTextFieldpublisher.getText().isEmpty()){
					jTextFieldpublisher.setText("");
					JOptionPane.showMessageDialog(null,"Publisher cannot be empty.");
					return;
				}
				//author
				if (jTextFieldauthor.getText().isEmpty()){
					jTextFieldauthor.setText("");
					JOptionPane.showMessageDialog(null,"Author cannot be empty.");					
					return;
				}
				//shopName
				if (jTextFieldshopName.getText().isEmpty()){
					jTextFieldshopName.setText("");
					JOptionPane.showMessageDialog(null,"ShopName cannot be empty.");
					return;
				}

				
				DBConection db = new DBConection();
			    db.openConn();
			    db.modifyBook(SelectedBookID, 
			    		jTextFieldprice.getText(),			    		
			    		jTextFieldISBN.getText(), 
			    		jTextFieldtitle.getText(), 
			    		jTextFieldpublisher.getText(),
			            jTextFieldauthor.getText(), 
			            jTextFieldshopName.getText());
			    db.closeConn();
			    JOptionPane.showMessageDialog(null,"A book has been Modified.");			    
			    jTextFieldprice.setText("");
			    jTextFieldISBN.setText("");
			    jTextFieldtitle.setText("");
			    jTextFieldpublisher.setText("");
			    jTextFieldauthor.setText("");
			    jTextFieldshopName.setText("");
				}

			

			private boolean validPrice(String text) {
				// TODO Auto-generated method stub
				try{
					return Double.parseDouble(text) > 0;
				}catch(NumberFormatException e){
					return false;
				}
			}
		});

        jButton2.setText("Delete");
        jButton2.addActionListener(new ActionListener() {
            
			public void actionPerformed(ActionEvent arg0) {
									
				DBConection db = new DBConection();
			    db.openConn();
			    db.deleteBook(SelectedBookID);			    
			    db.closeConn();
			    
			    JOptionPane.showMessageDialog(null,"A book has been Deleted.");			    
			    jTextFieldprice.setText("");
			    jTextFieldISBN.setText("");
			    jTextFieldtitle.setText("");
			    jTextFieldpublisher.setText("");
			    jTextFieldauthor.setText("");
			    jTextFieldshopName.setText("");
				}
			

		});
        
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelauthor)
                            .addComponent(jLabelprice, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jLabeltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldtitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jTextFieldprice)
                            .addComponent(jTextFieldauthor, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabeleISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabeletitle, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(jLabeleshopname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelpublisher)
                                    .addComponent(jLabelshopName))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldshopName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabeleauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelepublisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelprice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltitle)
                    .addComponent(jTextFieldtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelpublisher)
                    .addComponent(jTextFieldpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelauthor)
                    .addComponent(jTextFieldshopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelshopName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeleISBN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeletitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelepublisher)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabeleauthor))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(14, 14, 14)
                .addComponent(jLabeleshopname)
                .addGap(142, 142, 142))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyDeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyDeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyDeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyDeleteBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyDeleteBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelauthor;
    private javax.swing.JLabel jLabeleISBN;
    private javax.swing.JLabel jLabeleauthor;
    private javax.swing.JLabel jLabelepublisher;
    private javax.swing.JLabel jLabeleshopname;
    private javax.swing.JLabel jLabeletitle;
    private javax.swing.JLabel jLabelprice;
    private javax.swing.JLabel jLabelpublisher;
    private javax.swing.JLabel jLabelshopName;
    private javax.swing.JLabel jLabeltitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldauthor;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldpublisher;
    private javax.swing.JTextField jTextFieldshopName;
    private javax.swing.JTextField jTextFieldtitle;
    // End of variables declaration//GEN-END:variables
}
